### ISSUE TITLE
How to access the query parameters ?

### ISSUE THREAD

**Issue by vindarel** [eudoxia0/lucerne#24]
Hi,
I like the `with-params` macro, but I don't see something equivalent for the url query parameters. How can we access them ? I didn't find anything in the doc nor in the code. I bet they are in a clack `*request*` object, named `query-string`, but I don't know how to access them: clack [is not documented](http://quickdocs.org/clack/) and [this help](https://jasom.github.io/clack-tutorial/pages/getting-started-with-clack/) isn't clear on that (BTW, how to explore the `*request*` in slime's debugger, while I'm on a break for instance ? it only prints as "`CLACK:REQUEST<REQUEST>`")
Thanks

**Comment by macdavid313** [comment]
Please use `(clack.request:parameter *request* "your-query-string-here")`

**Comment by vindarel** [comment]
Thank you. I ended up with `(assoc "the-param" (clack.request:query-parameter lucerne:*request*) :test 'string=)`.

It would be nice if Lucerne provided a macro for that, similar to `with-params`. (Let's see if I come to write mine.)

doc to Clack api: http://quickdocs.org/clack/api#package-CLACK.REQUEST
