### ISSUE TITLE
:get method doesn't work

### ISSUE THREAD

**Issue by macdavid313** [eudoxia0/lucerne#6]
When I try this:

@route app "/index"
(defview hello ()
  (with-params (test)
    (respond (format nil "Hello, world! ~a" test))))

This doesn't work. Should print "Hello, world! lisp" when the url is "/index?test=lisp" ?

**Comment by eudoxia0** [comment]
Lucerne uses myway for routing, so you need to make that URL "/index*". This is, I'm pretty sure, a bug.

**Comment by eudoxia0** [comment]
After raising the issue on the myway repo and hearing that it's out-of-scope, I think I'll change the router to fix this.

**Comment by macdavid313** [comment]
'/index*' is acceptable for me, though a little bit of strange.  After this "problem" is fixed, will '/index*' still work?

**Comment by macdavid313** [comment]
Last comment has just been updated. I didn't notice Markdown syntax is supported.

**Comment by eudoxia0** [comment]
That is a good question. I'm not sure it would, I suppose it would depend on just how it was implemented. I'll have to write it first and see.

**Comment by macdavid313** [comment]
Oh OK, thanks for your work on this anyway :)
